# Generated by Django 3.2.16 on 2022-11-05 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curator',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
