# Generated by Django 3.2.16 on 2022-11-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='curator',
            name='phone',
            field=models.CharField(default='42', max_length=20),
            preserve_default=False,
        ),
    ]
